[build]
  publish = "publish"
  command = "pip install -r requirements.txt && python app.py"

[build.environment]
  # Set any environment variables required by your Flask app here
  PYTHON_VERSION = "3.8"  # or your desired Python version
